/*
 * This source file was generated by the Gradle 'init' task
 */
package com.group5.smartattendance;

import com.group5.smartattendance.gui.MainMenuView;
import com.group5.smartattendance.persistence.DatabaseManager;
import org.opencv.core.Core;

import javax.swing.SwingUtilities;

public class App {

    public static void main(String[] args) {
        DatabaseManager.initialize();
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        SwingUtilities.invokeLater(MainMenuView::new);
    }
}
