package com.group5.smartattendance.user;

import at.favre.lib.crypto.bcrypt.BCrypt;
import com.group5.smartattendance.persistence.UserDatabaseManager;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.Instant;

// manage users in the database
public class UserService {

    private static final Logger logger = LoggerFactory.getLogger(UserService.class);

    // sign up a new user
    public static User signup(String email, String fullName, String password) throws Exception {
        // input validation
        if (email == null || email.trim().isEmpty()) {
            throw new IllegalArgumentException("Email cannot be empty");
        }
        if (!isValidEmail(email)) {
            throw new IllegalArgumentException("Invalid email format");
        }
        if (fullName == null || fullName.trim().isEmpty()) {
            throw new IllegalArgumentException("Full name cannot be empty");
        }
        if (password == null || password.length() < 6) {
            throw new IllegalArgumentException("Password must be at least 6 characters long");
        }

        // check if email already exists
        if (getUserByEmail(email) != null) {
            throw new Exception("Email already exists");
        }

        // hash password with bcrypt
        // salt is automatically generated by bcrypt, no need to store it
        String passwordHash = BCrypt.withDefaults().hashToString(12, password.toCharArray());

        // insert into database
        Instant createdAt = Instant.now();
        String sql = "INSERT INTO users (email, full_name, password_hash, created_at) VALUES (?, ?, ?, ?)";
        try (Connection conn = UserDatabaseManager.getConnection();
                PreparedStatement stmt = conn.prepareStatement(sql, PreparedStatement.RETURN_GENERATED_KEYS)) {

            stmt.setString(1, email);
            stmt.setString(2, fullName);
            stmt.setString(3, passwordHash);
            stmt.setString(4, createdAt.toString());

            // if no rows were changed, throw an error
            if (stmt.executeUpdate() == 0) {
                throw new Exception("Failed to create user");
            }

            // get the generated ID
            try (ResultSet generatedKeys = stmt.getGeneratedKeys()) {
                if (generatedKeys.next()) {
                    String id = String.valueOf(generatedKeys.getInt(1));
                    logger.info("User created successfully: {}", email);
                    return new User(id, email, fullName, passwordHash);
                }
            }

            throw new Exception("Failed to retrieve user ID");

        } catch (SQLException e) {
            logger.error("Database error during signup: {}", e.getMessage());
            throw new Exception("Database error: " + e.getMessage());
        }
    }

    public static User login(String email, String password) throws Exception {
        if (email == null || email.trim().isEmpty()) {
            throw new IllegalArgumentException("Email cannot be empty");
        }
        if (password == null || password.isEmpty()) {
            throw new IllegalArgumentException("Password cannot be empty");
        }

        User user = getUserByEmail(email);
        if (user == null) {
            throw new Exception("Invalid email or password");
        }

        // verify password
        BCrypt.Result result = BCrypt.verifyer().verify(password.toCharArray(), user.getPasswordHash());
        if (!result.verified) {
            throw new Exception("Invalid email or password");
        }

        logger.info("User logged in successfully: {}", email);
        return user;
    }

    private static boolean isValidEmail(String email) {
        // regex thing
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
        return email.matches(emailRegex);
    }

    private static User getUserByEmail(String email) throws Exception {
        String sql = "SELECT id, email, full_name, password_hash, created_at FROM users WHERE email = ?";
        try (Connection conn = UserDatabaseManager.getConnection();
                PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setString(1, email);
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    String id = String.valueOf(rs.getInt("id"));
                    String userEmail = rs.getString("email");
                    String fullName = rs.getString("full_name");
                    String passwordHash = rs.getString("password_hash");

                    return new User(id, userEmail, fullName, passwordHash);
                }
            }

        } catch (SQLException e) {
            logger.error("Database error retrieving user: {}", e.getMessage());
            throw new Exception("Database error: " + e.getMessage());
        }

        return null;
    }
}
