/*
 * This source file was generated by the Gradle 'init' task
 */
package com.group5.smartattendance;

import org.junit.jupiter.api.Test;

import java.lang.reflect.Method;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class AppTest {
    @Test
    void appExposesMainEntryPoint() throws NoSuchMethodException {
        Method main = App.class.getDeclaredMethod("main", String[].class);
        assertNotNull(main, "App should declare a main entry point");
    }
}
